In [1]:
import numpy as np
revenue =np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [2]:
revenue-expenses

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [3]:
revenue*expenses

array([[14400, 18000, 22000],
       [  240,   576,   800],
       [   96,   180,   200]])

In [4]:
revenue+expenses

array([[260, 290, 320],
       [ 34,  52,  60],
       [ 20,  28,  30]])

In [5]:
revenue%expenses

array([[20, 20, 20],
       [ 4,  4,  0],
       [ 4,  8,  0]])

revenue/expenses

# Calculate total sales from units and price per unit using matrix multiplication


price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [16]:

price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [17]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [18]:
revenue*2

array([[360, 400, 440],
       [ 48,  72,  80],
       [ 24,  36,  40]])

# LOSS OR COST FUNCTION

In [37]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [38]:
def mae(y_true,y_predicted):
    total_error =0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print("total Error :",total_error)
    
    
    mae=total_error/len(y_true)
    print("MAE:" ,mae)
    return mae

In [39]:
mae(y_true,y_predicted)

total Error : 2.5
MAE: 0.5


0.5

In [41]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [42]:
np.sum(np.abs(y_predicted - y_true))*2

5.0

In [43]:
np.log([0.0000000000000000000000000000000001])

array([-78.28789316])

In [44]:
epsilon=1e-15

In [46]:
y_predicted

array([1, 1, 0, 0, 1])